### ISSUE TITLE
bottum tabs navigation

### ISSUE THREAD

**Issue by Sachinthana-Lokuyaddage** [CydexCode/CydexCode_Mobile_App#10]

**Comment by CydexCode** [comment]
done
![Uploading Screenshot 2024-07-10 143315.png…]()

**Comment by CydexCode** [comment]
![Screenshot 2024-07-10 143315](https://github.com/CydexCode/CydexCode_Mobile_App/assets/112784979/c592586c-29c5-480f-bafb-ab0a35f74497)
